export const authConfig = {
    authority: "https://auth.prod.orion.cz.foxconn.com/realms/OrionProd",
    redirectUrl: `${window.location.origin}/home`,
    authWellknownEndpointUrl: "https://auth.prod.orion.cz.foxconn.com/realms/OrionProd",
    clientId: "orionweb-dev-x698wqpF8lLaHEWfCVDkOoczTW",
    responseType: "code",
    scope: "openid profile",
    postLogoutRedirectUri: `${window.location.origin}/home`,
    startCheckSession: false,
    silentRenew: true,
    silentRenewUrl: `${window.location.origin}/silent-renew.html`,
    renewTimeBeforeTokenExpiresInSeconds: 10,
    postLoginRoute: "/dashboard",
    forbiddenRoute: "/forbidden",
    unauthorizedRoute: "/unauthorized",
    logLevel: 0,
    maxIdTokenIatOffsetAllowedInSeconds: 600,
    autoUserInfo: false,
    issValidationOff: true,
    triggerAuthorizationResultEvent: true,
    historyCleanupOff: true,
    storage: sessionStorage,
    useRefreshToken: true,
  }